### ISSUE TITLE
Failing because MASReceipt is missing

### ISSUE THREAD

**Issue by patgmac** [autopkg/scriptingosx-recipes#8]
Whenever I run a recipe which uses MASReceipt.py script, I get the error: 

Processing iMovie.pkg...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes/AppleCreativity/MASReceipt.py", line 61, in main
    os.rmdir(masreceipt_dir_path)
OSError: [Errno 2] No such file or directory: '/Users/pgalla2/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.iMovie/iMovie/Applications/iMovie.app/Contents/_MASReceipt'

This appears to be caused by the fact that the MASReceipt is deleted from the cached copy of $app. The initial run works as expected, subsequent runs fail with the above error. This prevents autopkg (or autopkgr) to run any recipes that come after it.

**Comment by scriptingosx** [comment]
Added a test wether the folder exists https://github.com/autopkg/scriptingosx-recipes/commit/3bdb1051d0f3464bb9bd4ff1b77839953c50d2ad

This should fix the immediate problem. However, if someone runs the recipe and then changes the MASReceipt behavior from 'delete' to dummy or nothing. The recipe will not see that change and assume the existing package is just fine.

Not sure how to address that, other than documentation, though.
