### ISSUE TITLE
Python3.download.recipe download error

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/scriptingosx-recipes#83]
Hi,
Seeing the below error when running this recipe. It looks like the URLs and the signing cert have changed
```Processor: URLTextSearcher: Error: No match found on URL: https://www.python.org/downloads/ ```

Changed the URLs to `https://www.python.org/downloads/macos` and this finds the installer fine, but the signing has changed:
```
CodeSignatureVerifier: Mismatch in authority names
CodeSignatureVerifier: Expected: Developer ID Installer: Ned Deily (DJ3H93M7VJ) -> Developer ID Certification Authority -> Apple Root CA
CodeSignatureVerifier: Found:    Developer ID Installer: Python Software Foundation (BMM5U3QVKW) -> Developer ID Certification Authority -> Apple Root CA}
```

Pull request incoming!

**Comment by fseesink** [comment]
Beat me to it. :smiley: 

I ran `autopkg run -vvv Python3.munki.recipe` and in the output I noticed
```
...
URLTextSearcher
{'Input': {'re_pattern': '(?P<url>https://.*/python-(?P<version_minor>3\\.\\d+)\\.\\d+.*\\.pkg)',
           'url': 'https://www.python.org/downloads/'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://www.python.org/downloads/
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No match found on URL: https://www.python.org/downloads/
Failed.
```

Just documenting here in case others go searching for this.
