### ISSUE TITLE
XQuartz.pkg.recipe error: FlatPkgUnpacker: Could not open package for expansion

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/scriptingosx-recipes#85]
Heya!
Looks like there's a mistake in the .pkg recipe for XQuartz that means FlatPkgUnpacker is trying to unpack the disk image, rather than the installer within:

```
% autopkg run -vvv com.github.scriptingosx.pkg.XQuartz
Processing com.github.scriptingosx.pkg.XQuartz...
WARNING: com.github.scriptingosx.pkg.XQuartz is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': '2.7',
 'BRANCH': 'release',
 'NAME': 'XQuartz',
 'PARENT_RECIPES': ['[REMOVED]/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/XQuartz/XQuartz.download.recipe'],
 'RECIPE_CACHE_DIR': '[REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz',
 'RECIPE_DIR': '[REMOVED]/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes/XQuartz',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '[REMOVED]/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes/XQuartz/XQuartz.pkg.recipe',
 'RECIPE_REPOS': {[REMOVED]]},
 'RECIPE_SEARCH_DIRS': ['.',
                        '[REMOVED]],
 'verbose': 3}
SparkleUpdateInfoProvider
{'Input': {'appcast_url': 'https://www.xquartz.org/releases/sparkle/release.xml'}}
SparkleUpdateInfoProvider: Version retrieved from appcast: 2.8.24
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: XQuartz-2.8.2
SparkleUpdateInfoProvider: Found URL https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.2/XQuartz-2.8.2.dmg
{'Output': {'url': 'https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.2/XQuartz-2.8.2.dmg',
            'version': 'XQuartz-2.8.2'}}
URLDownloader
{'Input': {'url': 'https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.2/XQuartz-2.8.2.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing [REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg
{'Output': {'pathname': '[REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'expected_authority_names': ['Developer ID Installer: Apple Inc. - '
                                        'XQuartz (NA574AWV7E)',
                                        'Developer ID Certification Authority',
                                        'Apple Root CA'],
           'input_path': '[REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg/XQuartz.pkg'}}
CodeSignatureVerifier: Mounted disk image [REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "XQuartz.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2022-07-01 03:21:45 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Apple Inc. - XQuartz (NA574AWV7E)
CodeSignatureVerifier:        Expires: 2026-01-05 20:30:38 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            AF 85 A2 FF 72 2D D9 0B B0 F4 5E 28 82 D8 AF 6B E3 61 EB 29 1D D9 
CodeSignatureVerifier:            B0 72 F1 90 89 7B 5D 6C CC 0C
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
{'Output': {}}
FlatPkgUnpacker
{'Input': {'destination_path': '[REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/unpack',
           'flat_pkg_path': '[REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/FlatPkgUnpacker.py", line 184, in main
    self.unpack_flat_pkg()
  File "/Library/AutoPkg/autopkglib/FlatPkgUnpacker.py", line 99, in unpack_flat_pkg
    self.pkgutil_expand()
  File "/Library/AutoPkg/autopkglib/FlatPkgUnpacker.py", line 154, in pkgutil_expand
    raise ProcessorError(
autopkglib.ProcessorError: extraction of [REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg with pkgutil failed: Could not open package for expansion: [REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg

  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
extraction of [REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg with pkgutil failed: Could not open package for expansion: [REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg

Failed.
Receipt written to [REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/receipts/com.github.scriptingosx.pkg-receipt-20230612-092206.plist

The following recipes failed:
    com.github.scriptingosx.pkg.XQuartz
        Error in com.github.scriptingosx.pkg.XQuartz: Processor: FlatPkgUnpacker: Error: extraction of [REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg with pkgutil failed: Could not open package for expansion:[REMOVED]/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.XQuartz/downloads/XQuartz-2.8.2.dmg

Nothing downloaded, packaged or imported.
```

PR incoming!
Daz

**Comment by grahampugh** [comment]
I think this PR was a mistake. There appears to be a package downloaded directly, not a dmg with a package inside it. The fact that this flips between dmg and pkg might need some investigation, but it's currently not working where as the previous version of the recipe was working for Quartz 2.8.5, which is the latest version: https://www.xquartz.org

**Comment by grahampugh** [comment]
EDIT: the Sparkle feed is simply out of date. One year out of date, in fact. Maybe they aren't updating it any more. Might be better to just scrape the https://www.xquartz.org/ web page directly.
